version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
      - environment:
          QT_VERSION_MAJOR: 5.13
          QT_VERSION: 5.13.2
          QT_DIST: /usr/local/Qt-"$QT_VERSION"
          QT_BASE_SRC: https://download.qt.io/official_releases/qt/"$QT_VERSION_MAJOR"/"$QT_VERSION"/submodules/qtbase-opensource-src-"$QT_VERSION".tar.xz
          QT_BASE_DIR: /qtbase-opensource-src-"$QT_VERSION"
          PATH: $QT_DIST/bin:$PATH
    steps:
      - run: apt-get update && apt-get -y install gcc g++ build-essential cmake bash libxcb1-dev libicu-dev libssl-dev linux-headers-generic curl git libxrender-dev \
      - run: apt-get -y install libpng3 libpng-dev libjpeg-turbo8 libjpeg-turbo8-dev libicu55 libicu-dev 
      - run: apt-get -y install libgles2-mesa libgles2-mesa-dev libfreetype6-dev libsqlite3-dev libgstreamer0.10-0 libgstreamer0.10-dev \
      - run: apt-get -y install  libogg-dev libvorbis-dev bzip2 gperf bison ruby flex && rm -rf /var/lib/apt/lists/*
      - run: curl -sSL $QT_BASE_SRC | tar xJ cd $QT_BASE_DIR && bash ./configure --help && bash ./configure -opensource -confirm-license -static -no-accessibility -sql-sqlite -sqlite -no-qml-debug -no-harfbuzz -openssl-linked -qt-pcre -no-dbus -nomake tools -no-xkbcommon-evdev -no-xinput2 -no-xcb-xlib -no-glib -qt-xcb -no-compile-examples -nomake examples -no-gif -qt-doubleconversion -no-gtk && make install

workflows:
  version: 2
  build_all:
    jobs:
      - build
